version: '3.8'

services:
  api:
    build:
      context: ./TaskManagementApi
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=/app/taskmanagement.db

  frontend:
    build:
      context: ./task-management-frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - api

volumes:
  sqlite_data: